services:
  api-service:
    image: deanfost/file-uploader-express
    ports:
      - 3000:3000
    env_file:
      - .env
  ui-service:
    image: deanfost/file-uploader-react
    ports:
      - 80:5000
    env_file:
      - .env
    depends_on:
      - api-service
    