services:
   api-service:
     image: deanfost/file-uploader-express
     ports:
       - 3000:3000
   ui-service:
     image: deanfost/file-uploader-react
     ports:
       - 80:5000
     depends_on:
       - api-service